import type { Metadata } from "next";
import Navbar from "@/component/layout/Navbar";
import { interDisplay, gambetta } from "@/lib/fonts";
import "./globals.css";
import NoiseOverlay from "@/component/ui/NoiseOverlay";
import SmoothScroll from "@/component/reusable/scroll/SmoothScroll";
import Footer from "@/component/layout/Footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${interDisplay.variable} ${gambetta.variable} h-full antialiased scroll-smooth`}>
      <body className="min-h-full flex flex-col font-sans bg-[#0a0a0a] text-white">
        <NoiseOverlay />
        <Navbar />
        <SmoothScroll>
          <div className="flex flex-col min-h-screen">
            <main className="flex-grow">{children}</main>
            <Footer />
          </div>
        </SmoothScroll>
      </body>
    </html>
  );
}
