import type { Metadata } from "next";
import Navbar from "@/component/layout/Navbar";
import { interDisplay, gambetta } from "@/lib/fonts";
import "./globals.css";
import SmoothScroll from "@/component/reusable/scroll/SmoothScroll";
import Footer from "@/component/layout/Footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${interDisplay.variable} ${gambetta.variable} antialiased`}>
      <body className="m-0 min-h-screen w-full overflow-x-hidden bg-[#0a0a0a] font-sans text-white">
        <Navbar />

        <SmoothScroll>
          <main>{children}</main>
          <Footer />
        </SmoothScroll>
      </body>
    </html>
  );
}
