import type { Metadata } from "next";
import Navbar from "@/component/layout/Navbar";
import { interDisplay, gambetta } from "@/lib/fonts";
import "./globals.css";
import NoiseOverlay from "@/component/ui/NoiseOverlay";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${interDisplay.variable} ${gambetta.variable} h-full antialiased scroll-smooth`}>
      <body className="min-h-full flex flex-col font-sans">
        <NoiseOverlay />
        <Navbar />
        {children}
      </body>
    </html>
  );
}
